apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::775505290799:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::775505290799:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1GI4QAK7MDMLE
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-05-21T18:53:01Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapUsers: {}
    manager: eksctl
    operation: Update
    time: "2021-05-21T18:53:01Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        f:mapRoles: {}
    manager: kubectl-patch
    operation: Update
    time: "2021-05-21T19:34:57Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "8668"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: fb897a96-f0ab-4ada-a9ec-03080aa684d6